package com.youtube.newbostonex1;

import javafx.fxml.FXML;
import javafx.scene.control.Button;
import javafx.event.ActionEvent;
import javafx.scene.control.Label;

public class SampleController {
	@FXML
	private Label label1;
	@FXML
    private Button button;
    
    private Main main;
	
	/**
	 * connect the Main class to the controller
	 * @param main
	 */
	public void setMain(Main main) {
		this.main = main;
	}

	// Event Listener on Button[#button].onAction
	@FXML
	public void handleButtonClick(ActionEvent event) {
		// TODO Autogenerated
	}
}
